# Generated by Django 5.1.7 on 2025-10-29 02:42

from django.db import migrations, models
from django.utils.timezone import now


class Migration(migrations.Migration):

    dependencies = [
        ('sermons', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sermon',
            options={},
        ),
        migrations.RenameField(
            model_name='sermon',
            old_name='audio_url',
            new_name='media_url',
        ),
        migrations.RenameField(
            model_name='sermon',
            old_name='speaker',
            new_name='preacher',
        ),
        migrations.RemoveField(
            model_name='sermon',
            name='video_url',
        ),
      

migrations.AddField(
    model_name='sermon',
    name='created_at',
    field=models.DateTimeField(auto_now_add=True, default=now),
    preserve_default=False,
),

        migrations.AddField(
            model_name='sermon',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='sermon',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
