# Generated by Django 5.1.7 on 2025-10-05 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_image_alter_event_date_alter_event_description_and_more'),
    ]

    operations = [
    ]
