# Generated by Django 5.1.7 on 2025-10-07 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_event_options_alter_eventregistration_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='event',
            unique_together={('title', 'date', 'location')},
        ),
    ]
