# Generated by Django 5.1.7 on 2025-10-24 05:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendancerecord',
            options={'verbose_name_plural': 'Attendance Records'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name_plural': 'Events'},
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'verbose_name_plural': 'Members'},
        ),
        migrations.AlterModelOptions(
            name='newspost',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'News Posts'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-date_sent'], 'verbose_name_plural': 'Notifications'},
        ),
        migrations.AlterModelOptions(
            name='prayerrequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Prayer Request', 'verbose_name_plural': 'Prayer Requests'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name_plural': 'Roles'},
        ),
        migrations.AlterModelOptions(
            name='volunteer',
            options={'verbose_name_plural': 'Volunteers'},
        ),
        migrations.RemoveField(
            model_name='prayerrequest',
            name='answered',
        ),
        migrations.RemoveField(
            model_name='prayerrequest',
            name='message',
        ),
        migrations.AddField(
            model_name='prayerrequest',
            name='description',
            field=models.TextField(default='Existing prayer request', help_text='Detailed description of the prayer request.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prayerrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Assigned', 'Assigned'), ('Answered', 'Answered')], default='Pending', help_text='Current prayer request status.', max_length=20),
        ),
        migrations.AddField(
            model_name='prayerrequest',
            name='team_assigned',
            field=models.CharField(blank=True, help_text='Optional name of the prayer team or pastor assigned.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='prayerrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='prayerrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='prayerrequest',
            name='is_private',
            field=models.BooleanField(default=False, help_text='If true, this request is only visible to church leaders.'),
        ),
        migrations.AlterField(
            model_name='prayerrequest',
            name='title',
            field=models.CharField(help_text='Short title for the prayer request.', max_length=150),
        ),
        migrations.AlterField(
            model_name='prayerrequest',
            name='user',
            field=models.ForeignKey(help_text='The user who submitted this prayer request.', on_delete=django.db.models.deletion.CASCADE, related_name='prayer_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='attendancerecord',
            unique_together={('member', 'date')},
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('method', models.CharField(choices=[('Cash', 'Cash'), ('Mpesa', 'Mpesa'), ('PayPal', 'PayPal'), ('Bank Transfer', 'Bank Transfer')], default='Cash', max_length=50)),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_donations', to='accounts.member')),
            ],
            options={
                'verbose_name_plural': 'Donations',
            },
        ),
    ]
