# Generated by Django 5.1.7 on 2025-10-24 11:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_newspost_options_newspost_author_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-date_sent']},
        ),
        migrations.AlterModelOptions(
            name='prayerrequest',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='newspost',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='prayerrequest',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='prayerrequest',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='prayerrequest',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='prayerrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Assigned', 'Assigned'), ('Answered', 'Answered')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='prayerrequest',
            name='team_assigned',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='prayerrequest',
            name='title',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='prayerrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prayer_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
