# Generated by Django 5.1.7 on 2025-10-24 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='Donation',
        ),
    ]
