# Generated by Django 5.1.7 on 2025-11-01 13:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_mediaitem_delete_media'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prayerrequest',
            options={},
        ),
        migrations.RemoveField(
            model_name='prayerrequest',
            name='status',
        ),
        migrations.RemoveField(
            model_name='prayerrequest',
            name='team_assigned',
        ),
        migrations.AddField(
            model_name='prayerrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='prayerrequest',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='PrayerReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prayer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prayreactions', to='accounts.prayerrequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prayer_reactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'unique_together': {('prayer', 'user')},
            },
        ),
        migrations.AddField(
            model_name='prayerrequest',
            name='reactions',
            field=models.ManyToManyField(blank=True, related_name='prayed_requests', through='accounts.PrayerReaction', to=settings.AUTH_USER_MODEL),
        ),
    ]
